apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-devops
  template:
    metadata:
      labels:
        app: api-devops
    spec:
      containers:
      - name: api-devops
        image: api-devops:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
